remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "NOVA-3D: Non-overlapped Views for 3D Anime Character Reconstruction"
description: "Anonymous"
show_downloads: false

github:
  zip_url: http://example.com/download.zip
  another_url: another value
